### ISSUE TITLE
Homepage in theme.toml points to example.com

### ISSUE THREAD

**Issue by digitalcraftsman** [jsnjack/kraiklyn#1]
Hi @jsnjack,

after adding your theme I noticed that the [homepage linked in `theme.toml` points to www.example.com](https://github.com/jsnjack/kraiklyn/blob/master/theme.toml#L8). Once a URL is set it will be displayed on the theme site.

Some users might be confused by this links. Hence I suggest to leave the `homepage` variable empty or you add the domain to your website if you like.

**Comment by jsnjack** [comment]
@digitalcraftsman thank you for reporting it! I changed it to the github page
