### ISSUE TITLE
Nested directories creates index and content duplication

### ISSUE THREAD

**Issue by WeeKnightGames** [jsnjack/kraiklyn#13]
As demonstrated in https://github.com/WeeKnightGames/kraiklyn-duplication,

When I have 
```
├───content
│   └───intro
│       │   file.md
│       │   _index.md
│       │
│       └───subdir
│               _index.md
```

The resultant page that Kraiklyn builds creates the following index (duplicating the `Subdir` header); and duplicates the content of `subdir/_index.md` in the page.

```
Intro
    Subdir
    Subdir
    File
```

**Comment by jsnjack** [comment]
Hi! Thank you for reporting it. Should be fixed now :)
