### ISSUE TITLE
Images missing max-width property

### ISSUE THREAD

**Issue by paskal** [jsnjack/kraiklyn#2]
Hello!

I've stumbled upon the very same issue as the https://github.com/dim0627/hugo_theme_beg/issues/19, only part of the image visible on the screenshot where whole should be:

![image](https://user-images.githubusercontent.com/712534/37682940-f4db5258-2c9b-11e8-8793-4ed0a15a2a8c.png)

Source code:

    ![Shinken simple distributed architecture](https://shinken.readthedocs.io/en/latest/_images/shinken-architecture.png)

**Comment by jsnjack** [comment]
Hi! Thank you for reporting it! :)
