### ISSUE TITLE
css not found

### ISSUE THREAD

**Issue by andrearicci** [jsnjack/kraiklyn#5]
Hallo, and thank you for the nice template.
I found a defect about the css generated links: they start with a / so the html does'n find them, like:
```
<link rel="stylesheet" href="/css/styles.css">
<link rel="stylesheet" href="/css/custom.css">
```
instead of
```
<link rel="stylesheet" href="css/styles.css">
<link rel="stylesheet" href="css/custom.css">
```
Also the style 
`.block.war`
is called _warning_ in the html, so the styling is lost.
Thank you

**Comment by jsnjack** [comment]
Hi! Thank you for reporting issues!

I don't think the issue 1 is actually an issue. Have you tried to set baseURL in site config?

Issue 2: I fixed incorrect documentation. Please use `warn` instead of `warning`

**Comment by andrearicci** [comment]
Hi, yes my baseurl was "/", sorry.
