### ISSUE TITLE
anchor doesn't appear to work quite right

### ISSUE THREAD

**Issue by WeeKnightGames** [jsnjack/kraiklyn#6]
I'm seeing the same thing in my site, when putting `[Bora Horza Gobuchul]({{% anchor "characters/bora.md" %}})` into a file, the `anchor` is expanded to something like `#bora%20%20%20 #bora` rather than `#bora`.

**Comment by jsnjack** [comment]
Hey! Thank you for reporting the issue! Could you please provide more information on how to reproduce it? (link to the repo or just code sample will do)

**Comment by jsnjack** [comment]
Hm.. I can see that the generated link is not correct on themes.gohugo.io portal. However, if I run the example website locally everything works fine. I think it might be something to do with the way how they serve the example website :/

**Comment by WeeKnightGames** [comment]
Huh, I've pushed a version that breaks for me to https://github.com/WeeKnightGames/fourth-world-srd/blob/demonstrate-anchor-bug/content/classes/_index.md#L14 (this line breaks for me:

```
- [Shaman]({{% anchor "classes/shaman.md" %}}) (Primal Support)
```

**Comment by jsnjack** [comment]
I have just cloned and tested your repository. Works perfectly fine. What hugo version do you use?

**Comment by WeeKnightGames** [comment]
*Hugo Static Site Generator v0.45 windows/amd64 BuildDate: 2018-07-22T12:10:05Z*

And you checked out the `demonstrate-anchor-bug` branch?

**Comment by jsnjack** [comment]
I have just checked on `demonstrate-anchor-bug` branch. Also works fine.

However, I have hugo 0.34. Will check on the latest too
