### ISSUE TITLE
Sections aren't processed unless Pages also exist

### ISSUE THREAD

**Issue by thowe** [jsnjack/kraiklyn#8]
In layouts/partials/menu_page_list.html and layouts/partials/section_list.html
Sections won't be processed/displayed unless there are also Pages to display.  This is because .Sections isn't checked unless you have already determined that .Pages is not empty.

One simple way I fixed this is as follows:
```
{{ partial "section.html" . }}
{{ range .Sections.ByWeight }}
    {{ partial "section_list.html" . }}
{{ end }}
{{ range .Pages.ByWeight }}
    {{ partial "section.html" . }}
{{ end }}
```

and
```
    <li>
        <a href="#{{ .Params.anchor }}">{{ .Title }}</a>
{{ if or .Pages .Sections }}
        <ul>
    {{ range .Sections.ByWeight }}
        {{ partial "menu_page_list.html" . }}
    {{ end }}
    {{ range .Pages.ByWeight }}
            <li><a href="#{{ .Params.anchor }}">{{ .Title }}</a></li>
    {{ end }}
        </ul>
{{ end }}
    </li>
```

This fixes the problem of getting sections to display and simplifies the code a bit, however there is still another problem that is not solved...  Pages and Sections should be intermixed with each other, however they will be sorted separately by weight from each other so that all sections display first and all pages display second.  To fix this, they would need to be sorted together.  I've only just started looking at Hugo this weekend, so I'm not sure how to do that yet.  I'll look into that a bit once I have that need and, perhaps, submit a pull request.

**Comment by jsnjack** [comment]
Hi thowe! Thank you reporting the issue. Could you please provide a site example or a content directory structure? I'm not sure how to reproduce the issue (and what is the issue :) )
