### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by retr0h** [jsnjack/kraiklyn#9]
I noticed in the example kraiklyn theme [screenshot](https://github.com/jsnjack/kraiklyn/blob/master/images/screenshot.png) there is an nice centered image above Consider Phlebas.  I have added my own header.html and image, but I cannot get it to center.  Could you provide the details on how this was accomplished with your theme?  Thanks.

**Comment by jsnjack** [comment]
1. Create your own `partials/logo.html` file to replace the one that comes with the theme
2. use `text-align: center` CSS rule to center the element (svg object in the example)

**Comment by retr0h** [comment]
Thanks jsnjack.  What I ended up doing for others.

In `partials/logo.html`:
```
<div style="text-align:center">
  <img src="/images/io.svg">
</div>
```
